services:
  _defaults:
    # Automatically injects dependencies in your services
    autowire: true

    # Automatically registers your services as commands, event subscribers, etc.
    autoconfigure: true

    # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work
    public: false

  app.sylius_payment:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [ Filcronet\SyliusSetefiPlugin\Payum\SetefiPaymentGatewayFactory ]
    tags:
      - { name: payum.gateway_factory_builder, factory: setefi_payment }

  Filcronet\SyliusSetefiPlugin\Form\Type\SetefiGatewayConfigurationType:
    tags:
      - { name: sylius.gateway_configuration_type, type: setefi_payment, label: 'Setefi Payment' }
      - { name: form.type }

  Filcronet\SyliusSetefiPlugin\Payum\Action\CaptureAction:
    public: true
    arguments:
      - '@sylius.http_client'
      - '@request_stack'
      - '@monolog.logger'
    tags:
      - { name: payum.action, factory: setefi_payment, alias: payum.action.capture }

  #setefi.controller:
  #  class: Filcronet\SyliusSetefiPlugin\Controller\SetefiController
  #  autowire: true
  #  public: true
  #  tags: ['controller.service_arguments']
